logger:
  file:
    path: /var/log/open5gs/nrf.log

global:
  # Add any global configurations like API versions or common parameters here
  api:
    version: 1.0

nrf:
  sbi:
    server:
      - address: nrf.open5gs.org  # Make sure the address is resolvable or replace with a proper IP address
        port: 80

  # Adding heartbeat and subscriptions
  heartbeat: 10  # Set the heartbeat interval (seconds)
  subscriptions:
    - nf_id: a33e490a-bbb9-41ef-9c3d-252eb0af11bf
      nf_type: AMF
      valid_until: "2024-12-17T14:25:45"

  # Configuration for FQDNs for registered Network Functions (NFs)
  fqdns:
    - amf.open5gs.org
    - bsf.open5gs.org
    - nssf.open5gs.org
    - ausf.open5gs.org
    - udm.open5gs.org

  # Optional: Define additional parameters specific to your network
  config:
    nf_type: NRF  # Define the type of network function
    name: Open5GS NRF  # The name for this network function

