db_uri: mongodb://db.open5gs.org/open5gs

logger:
  file: /open5gs/install/var/log/open5gs/bsf.log

bsf:
  sbi:
    - name: bsf.open5gs.org
      port: 80

scp:
  sbi:
    - name: scp.open5gs.org
      port: 80

parameter:

max:

time:
