logger:
  file: /open5gs/install/var/log/open5gs/nssf.log

nssf:
  sbi:
    - name: nssf.open5gs.org
      port: 80
  nsi:
    - name: nrf.open5gs.org
      port: 80
      s_nssai:
        sst: 1

scp:
  sbi:
    - name: scp.open5gs.org
      port: 80

parameter:

max:

time:
