logger:
  file:
    path: /open5gs/install/var/log/open5gs/udm.log

global:

udm:
  sbi:
    server:
      - address: udm.open5gs.org
        port: 80
    client:
      scp:
        - uri: http://scp.open5gs.org:80
