logger:
  file: /open5gs/install/var/log/open5gs/amf.log

sbi:
  server:
    no_tls: true
    cacert: /open5gs/install/etc/open5gs/tls/ca.crt
    key: /open5gs/install/etc/open5gs/tls/amf.key
    cert: /open5gs/install/etc/open5gs/tls/amf.crt
  client:
    no_tls: true
    cacert: /open5gs/install/etc/open5gs/tls/ca.crt
    key: /open5gs/install/etc/open5gs/tls/amf.key
    cert: /open5gs/install/etc/open5gs/tls/amf.crt

amf:
  sbi:
    - name: amf.open5gs.org
      port: 80
  ngap:
    - name: amf.open5gs.org
  metrics:
      name: amf.open5gs.org
      port: 9090
  guami:
    - plmn_id:
        mcc: 001
        mnc: 01
      amf_id:
        region: 2
        set: 1
  tai:
    - plmn_id:
        mcc: 001
        mnc: 01
      tac: 1
  plmn_support:
    - plmn_id:
        mcc: 001
        mnc: 01
      s_nssai:
        - sst: 1
  security:
      integrity_order : [ NIA2, NIA1, NIA0 ]
      ciphering_order : [ NEA0, NEA1, NEA2 ]
  network_name:
      full: Open5GS
  amf_name: open5gs-amf0

nrf:
  sbi:
    - name: nrf.open5gs.org
      port: 80

parameter:

max:

usrsctp:

time:
  t3512:
    value: 540
