logger:
  file: /open5gs/install/var/log/open5gs/nrf.log

sbi:
  server:
    no_tls: true
    cacert: /open5gs/install/etc/open5gs/tls/ca.crt
    key: /open5gs/install/etc/open5gs/tls/nrf.key
    cert: /open5gs/install/etc/open5gs/tls/nrf.crt
  client:
    no_tls: true
    cacert: /open5gs/install/etc/open5gs/tls/ca.crt
    key: /open5gs/install/etc/open5gs/tls/nrf.key
    cert: /open5gs/install/etc/open5gs/tls/nrf.crt

nrf:
  sbi:
    - name: nrf.open5gs.org
      port: 80

parameter:

max:

time:
