logger:
  file: /open5gs/install/var/log/open5gs/smf.log

global:
  max:
    ue: 1024

smf:
  sbi:
    server:
      - address: smf.5gc.mnc001.mcc001.3gppnetwork.org
        port: 80
    client:
      nrf:
        - uri: http://nrf.5gc.mnc001.mcc001.3gppnetwork.org:80
  pfcp:
    server:
      - address: smf.5gc.mnc001.mcc001.3gppnetwork.org
    client:
      upf:
        - address: upf.5gc.mnc001.mcc001.3gppnetwork.org
  gtpc:
    server:
      - address: smf.5gc.mnc001.mcc001.3gppnetwork.org
  gtpu:
    server:
      - address: smf.5gc.mnc001.mcc001.3gppnetwork.org
  session:
    - subnet: 10.45.0.1/16
  dns:
    - 8.8.8.8
    - 8.8.4.4
  mtu: 1400
