logger:
  file:
    path: /var/log/open5gs/ausf.log

global:

ausf:
  sbi:
    server:
      - address: ausf.open5gs.org
        port: 80
    client:
      scp:
        - uri: http://scp.open5gs.org:80
