db_uri: mongodb://db.open5gs.org/open5gs

logger:
  file:
    path: /var/log/open5gs/udr.log

global:

udr:
  sbi:
    server:
      - address: udr.open5gs.org
        port: 80
    client:
      scp:
        - uri: http://scp.open5gs.org:80
