logger:
  file: /open5gs/install/var/log/open5gs/nssf.log

sbi:
  server:
    no_tls: true
    cacert: /open5gs/install/etc/open5gs/tls/ca.crt
    key: /open5gs/install/etc/open5gs/tls/nssf.key
    cert: /open5gs/install/etc/open5gs/tls/nssf.crt
  client:
    no_tls: true
    cacert: /open5gs/install/etc/open5gs/tls/ca.crt
    key: /open5gs/install/etc/open5gs/tls/nssf.key
    cert: /open5gs/install/etc/open5gs/tls/nssf.crt

nssf:
  sbi:
    - name: nssf.open5gs.org
      port: 80
  nsi:
    - name: nrf.open5gs.org
      port: 80
      s_nssai:
        sst: 1
        sd: 000001
    - name: nrf.open5gs.org
      port: 80
      s_nssai:
        sst: 1
        sd: 000002

nrf:
  sbi:
    - name: nrf.open5gs.org
      port: 80

parameter:

max:

time:
