logger:
  file: /open5gs/install/var/log/open5gs/smf.log

global:
  max:
    ue: 1024

smf:
  sbi:
    server:
      - address: smf1.open5gs.org
        port: 80
    client:
      nrf:
        - uri: http://nrf.open5gs.org:80
  pfcp:
    server:
      - address: smf1.open5gs.org
    client:
      upf:
        - address: upf1.open5gs.org
  gtpc:
    server:
      - address: smf1.open5gs.org
  gtpu:
    server:
      - address: smf1.open5gs.org
  session:
    - subnet: 10.45.0.1/16
  dns:
    - 8.8.8.8
    - 8.8.4.4
  mtu: 1400
  info:
    - s_nssai:
      - sst: 1
        sd: 000001
        dnn:
          - internet
      tai:
        - plmn_id:
            mcc: 001
            mnc: 01
          tac: 1
