logger:
  file: /open5gs/install/var/log/open5gs/upf.log

upf:
  pfcp:
    - addr: upf1.open5gs.org
  gtpu:
    - addr: upf1.open5gs.org
  subnet:
    - addr: 10.45.0.1/16
      dnn: internet

smf:

parameter:

max:

time:
